# TODO: explain it
name: flavilarocca

# TODO: explain it
# subdomain: sample

# TODO: explain it
domains: [www.flavialarocca.com, flavialarocca.com]

# TODO: explain it
locales: [en]

# TODO: explain it
seo_title: flavialarocca
meta_keywords: "some meta keywords"
meta_description: "some meta description"